### ISSUE TITLE
Version 1.1.11 breaks python highlighting

### ISSUE THREAD

**Issue by cijkod** [Monokai/monokai-pro-vscode#120]
After upgrading to version 1.1.11 python highlighting changes, function calls are no longer highlighted in green, instead they are highlighted in white which makes it harder to see them.

**Comment by JasonIRL** [comment]
I am experiencing the same issue

**Comment by Monokai** [comment]
I've removed some scopes in 1.1.11 due to errors in C++ syntax highlighting. That also had an effect on Python unfortunately. It would be better if syntax definitions of Python should also be fixed, but that's something I don't have control over. It uses a lot of `meta.*` scoping, like `meta.function-call`, which, according to [the docs for Sublime Text](https://www.sublimetext.com/docs/3/scope_naming.html#meta) (which uses the same scoping syntax), are not to be used for styling. Unfortunately, it's the only scope that's available in the VSCode Python language definition.

Anyway, fixed in 1.1.12!
