### ISSUE TITLE
Problems after update (1.1.0)

### ISSUE THREAD

**Issue by bsvipas** [Monokai/monokai-pro-vscode#15]
**I'm using Monokai Pro without filters and I found some problems.**
VS Code:  1.16.0

## 1
![image](https://user-images.githubusercontent.com/30043375/29889818-30373ffa-8dce-11e7-9530-5ee4db9c1748.png)
`window.navigator` and `window.location` have different colors (blue/white), I don't know which one is correct, but I think they need to look same.

## 2
![image](https://user-images.githubusercontent.com/30043375/29889836-4030d93e-8dce-11e7-9736-3dbc23b7dff6.png)
`download` property have different color than others.

![image](https://user-images.githubusercontent.com/30043375/30259331-65e0dd38-96c9-11e7-8bbf-0615bcf8e955.png)
`this.name` and `this.age` colors are different.

## 3
![image](https://user-images.githubusercontent.com/30043375/29889875-675c6dde-8dce-11e7-8814-affdfe2b8bb2.png)
disabled attribute color same as brackets, I don't know if it's wrong, but as far as I remember it was different before 1.1.0.

**Comment by Monokai** [comment]
Monokai Pro uses scopes to determine its colors. These scopes are derived from language syntax definitions. You can inspect the scopes in VSCode via the command palette: "Developer: Inspect TM Scopes". I have to work with whatever the language syntax definitions give me. If you look at your cases, "location" has a different scope than "navigator". I think the language definition is wrong here. Same is true for "download" & "target" and "name" and "age". Although the latter is maybe hard to fix, as its a property of "this" instead of a dom object, which is a hard for language definitions to distinguish.

Only thing that I don't know yet is number 3. Can you give me an example in context?

**Comment by bsvipas** [comment]
The number 3 is handlebars files, but it looks good right now for me. So as far as I understand this is unfixable right now and it will be like it is?

**Comment by Monokai** [comment]
Yes I guess so, until somebody comes along and fixes the language definition itself. But this is maintained outside of Monokai Pro.

**Comment by bsvipas** [comment]
@Monokai Yep, you was right, I tried to use `Inspect TM Scopes` and I saw it's of bad language definitions in VS Code. I will try to open an issue in VS Code.

**Comment by bsvipas** [comment]
@Monokai https://github.com/Microsoft/TypeScript-TmLanguage/issues/523
