### ISSUE TITLE
1.1.17 also changes template string placeholder color

### ISSUE THREAD

**Issue by monotykamary** [Monokai/monokai-pro-vscode#201]
I noticed that the newest version documented reverted const variable highlighting, but didn't have any documentation about template string placeholder highlights which is different in the newest version. I was wondering if this is intentional and just undocumented.

<=1.1.16:
![image](https://user-images.githubusercontent.com/1130103/84218851-77b2b300-aaf9-11ea-8d44-bd4090ed4e06.png)

1.1.17:
![image](https://user-images.githubusercontent.com/1130103/84218864-813c1b00-aaf9-11ea-9eec-b9604e8fc3b4.png)

**Comment by Monokai** [comment]
It's intentional. To show better that you're breaking out of the string. There's also an argument to be made for the previous version, to dim the placeholder and focus on the content. To be honest I'm 50/50 here. I changed this to make it more in line with Sublime Text and its Javascript / Javascript Next syntax. Any feedback welcome!
