### ISSUE TITLE
Monokai Pro is not an available extension for vscodium

### ISSUE THREAD

**Issue by adrinux** [Monokai/monokai-pro-vscode#204]
Just switched to the open source builds of vscode by the [vscodium](https://vscodium.com/) project and Monokai Pro isn't listed in the available extensions. Is Monokai Pro only supported on the Microsoft builds (telemetry and all)?

I found a workaround (I'm running on manjaro Gnome Linux):
```
cp -r .vscode/extensions/monokai.theme-monokai-pro-vscode-1.1.17 .vscode-oss/extensions
```
Restarted vscodium and was then able to both select Monokai Pro as theme and bring up the enter license command.

**Comment by jamesgecko** [comment]
This happens because only official builds of Visual Studio Code are allowed to install extensions from the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/vscode). Third party builds and forks of VSCode (or editors compatible with VSCode's extension format) must use a third party extension repository. Folks seem to have settled on [Open VSX](https://open-vsx.org/) as the community-run alternative.

It'd be great to have Monokai Pro available on Open VSX, because manual installation of the extension is currently the only way to get the theme in editors like VSCodium, [Theia](https://theia-ide.org/), or [Onivim2](https://www.onivim.io/).

**Comment by zeitchef** [comment]
I'm able to install marketplace plugins in VSCodium following these easy steps:

https://www.chrisatmachine.com/Neovim/22-vscodium-neovim/

If you update VSCodium, you'll need to repeat this however.

**Comment by Monokai** [comment]
Monokai Pro is now live in the open vsx market place: https://open-vsx.org/extension/monokai/theme-monokai-pro-vscode
