### ISSUE TITLE
Classes in HTML and className in JSX are colored as strings

### ISSUE THREAD

**Issue by ajitid** [Monokai/monokai-pro-vscode#23]
While IDs share same color in HTML and CSS, classes of HTML and className of JSX doesn't.

**Comment by Monokai** [comment]
I can only color the scope that the syntax definitions give me. If you do "command palette > Developer: Inspect TM Scopes" there's no class information in the case of HTML for example. So that means I cannot distinguish between strings and classes.

For example, Sublime Text has slightly different syntax definitions that do make this distinction and Monokai Pro is able to style classes and IDs differently there.
