### ISSUE TITLE
I purchased a license and did not received my email ...

### ISSUE THREAD

**Issue by ObieSilva** [Monokai/monokai-pro-vscode#233]
Hello I purchased a license for VSCode and got charged 2 dollars more and also did not received an email confirmation with my license details.

**Comment by Monokai** [comment]
Hi, could you please mail me at hello at monokai.pro so I can look up your payment? Sometimes there's a spelling mistake in the email address and sometimes the email is caught in a spam folder.

The price of €9.95 is in EUR, not in USD. I haven't checked the latest EUR/USD exchange rates, but I think the difference is caused by that.
