### ISSUE TITLE
Regex highlighting issue

### ISSUE THREAD

**Issue by yeysman** [Monokai/monokai-pro-vscode#244]
Please see the attached screenshot.
![image](https://user-images.githubusercontent.com/3490139/111433696-4cec2f80-8707-11eb-81cf-d8c54ac053eb.png)

Could you please fix this issue? 
It is very confusing when the code contains long expressions with square brackets.

**Comment by Monokai** [comment]
Unfortunately this is caused by the PHP syntax definitions of VSCode and not by the theme. Monokai Pro uses the syntax definitions of VSCode to color different parts of the RegEx, but it seems the syntax definition of PHP erroneously tags this as a punctuation character. You can see for yourself if you enable "Inspect editor tokens and scopes" from the command palette. Each language has its own syntax definitions. The same RegEx is seems to be correctly colored in Javascript for example.

**Comment by yeysman** [comment]
Hello Monokai,
Thank you for your reply. 
Please see how default themes colorize this regex expression in PHP below. 
For example 
Vscode Dark (default)
![image](https://user-images.githubusercontent.com/3490139/113813270-3d955a80-9778-11eb-8c9c-aa76e3c61d6c.png)
Or Github dark (custom theme)
![image](https://user-images.githubusercontent.com/3490139/113813309-569e0b80-9778-11eb-908c-ea0e5e7331ca.png)

Is it possible to make it works similar to one of those themes?
