### ISSUE TITLE
String Expressions not correctly highlighted in .erb files (`#{...}` )

### ISSUE THREAD

**Issue by dylansheffer** [Monokai/monokai-pro-vscode#29]
The closing bracket isn't highlighted orange like the opening bracket. I was only able to reproduce this inside the Monokai Pro themes, so I do not believe it is another plugin that is causing the issue.

Screenshot: 
![image](https://user-images.githubusercontent.com/16800400/31457000-755a9bf0-ae89-11e7-8100-89a1989f06b1.png)

Active Plugins:
Ruby: by Peng Lv (v0.15.0)
vscode-icons: by Roberto Huertas (v7.15.0)

**Comment by Monokai** [comment]
This might be part of the syntax definition, which is something else than syntax highlighting. Monokai Pro handles the highlighting, VSCode handles the syntax definition. I did some investigation. If you go to command palette: `Inspect TM scopes`, you see the following scope at the opening bracket:

```
punctuation.section.embedded.begin.ruby
meta.embedded.line.ruby
string.quoted.double.ruby
source.ruby                                                                                                                                                            
```

You read this from bottom to top, from more generally defined scopes, to more specific. So this seems right, you have the ruby source, which contains a string, which contains an embedded line, of which the punctuation is the most specific scope selector, which is used to color it orange.

In the middle of the string, it's something like:
```
source.ruby
meta.embedded.line.ruby
string.quoted.double.ruby
source.ruby
```

Important to notice is that we have an embedded `source.ruby` inside a `source.ruby`.

If you do this at the end, you see:
```
source.ruby
punctuation.section.embedded.end.ruby
meta.embedded.line.ruby
string.quoted.double.ruby
source.ruby
```

Again, we have an embedded `source.ruby` inside `source.ruby`. And I think that's the problem. The second `source.ruby` shouldn't be there, because the bracket should be the terminator of the embedded source scope. So I think the bug is in the syntax definition, instead of the color scheme.
