### ISSUE TITLE
Licence issue.

### ISSUE THREAD

**Issue by chichikinaleksei** [Monokai/monokai-pro-vscode#325]
Hi there. I bought a licence some time ago for VS code. 
Now while I use it I always get this popup with licence reminder. How do I connect or link my VS code to Monokai pro licence.
Thank you.

**Comment by Monokai** [comment]
Please refer to your license email with instructions. You can enter the license information via `menu > view > command palette` and then select `Monokai Pro: enter license`.

**Comment by 1RandomDev** [comment]
You can probably fix this problem all together completely for free just by adding a simple return statement to the main.js file 😂

**Comment by WinkelCode** [comment]
> You can probably fix all license problems together completely for free just by adding a simple return statement to the main.js file 😂

The key generation algorithm isn't exactly a well hidden secret... Besides, it's pretty much already freeware, just with some pop ups (sometimes called nagware). I didn't purchase a key because I couldn't use the theme otherwise, I bought it because I tried A LOT of themes and Monokai Pro is the only one that works for me and the price is completely fair. Especially once you get into commercial use, being able to use a product != should be using a product. I am just happy that the developer isn't using some annoying form of DRM, I think it makes it perfectly clear that the theme isn't a free product, which I find perfectly OK.

**Comment by tailessfish** [comment]
I bought a licence, but dont't receive any email form my inbox. 
my eamail is twistplok@gmail.com
