### ISSUE TITLE
Is it possible to have a file icon theme set with a folder icon?

### ISSUE THREAD

**Issue by cliffkoh** [Monokai/monokai-pro-vscode#35]
I find myself switching to "Nomo Dark" file icon theme just because they have a folder icon - it helps align everything in a way that makes it easier to parse file/folder structure for me...

**Comment by cascalheira** [comment]
+1 - Without this i am also using another theme.

**Comment by Monokai** [comment]
I think it's superfluous if there's a double icon (arrow + folder icon). What I actually want is to define the arrow icons and to better align folders and files. At the moment this is not possible in VSCode.

**Comment by dhensen** [comment]
@Monokai I agree with you on the arrow + folder icon. Your theme is awesome and I am currently considering buying it. The only problem I have is that my eyes can not adjust to the icon theme without folder icons... but that is not really the problem. My real problem is that the file-icon placement due to lack of the folder icons. Because of the lack of file-icon indent it takes too much effort to see what files belong to which folder.

**Comment by Monokai** [comment]
VSCode added support for custom arrow icons and In 1.1.6 I implemented that. It's up to VSCode now to adjust the indent.

**Comment by MillhioreBT** [comment]
4 years and monokai still doesn't add folder icons xd
😭
