### ISSUE TITLE
Monokai Pro in c++ code did not render colors right in code editor, but correct in hover 

### ISSUE THREAD

**Issue by DvdBr3o** [Monokai/monokai-pro-vscode#385]
![image](https://github.com/Monokai/monokai-pro-vscode/assets/77841210/ea8c8563-436c-41b4-86ed-887cedee857a)

This is a piece of c++ code. 

The color of `std::wstring` should have been rendered as **white** for `std`, **blue** for `wstring`.

However, it was rendered **green** for `std`, **white** for `wstring`.

The correct render result should have been the one presented in the hover.

I'm not sure whether this is something to do with monokai pro, since I've tried other themes as well, some of which performs right while some don't.

This is only one instance, something like **blue** for **macros** being rendered as **white** could also be seen below:

![image](https://github.com/Monokai/monokai-pro-vscode/assets/77841210/1b198cf4-f65a-4760-9df5-836f963c13ed)

`GLFW_TRANSPARENT_FRAMEBUFFER`, `GLFW_TRUE`, `GLFW_DECORATED` in this case.

The LSP is **clangd**.

I could quite assure that when i prevoiusly use monokai pro, they performed correctly. While somehow they don't now. :(

**Comment by Jas0nG** [comment]
I encountered a similar problem when I switched my LSP from the VS Code C/C++ to clangd.

![image](https://github.com/Monokai/monokai-pro-vscode/assets/43446377/ae905127-2578-4d87-a4b0-eb8f482e8aac)

The class name **Widget** wasn't highlight properly .

I checked token by [Scope inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) : `Developer: Inspect Editor Tokens and Scopes`.

![image](https://github.com/Monokai/monokai-pro-vscode/assets/43446377/41271d89-6eb1-4f98-9962-7c33038dbc0a)

It revealed that the class name 'Widget' and the object 'widget' were both mistakenly classified as 'source' and lacked semantic tokens, which is why they appeared in white. However, the hover feature correctly identifies the type of 'Widget', indicating that clangd's semantic tokenization is functioning correctly, but the semantic highlighting is not.

**Reference to [Enablement of semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#enablement-of-semantic-highlighting), I adjusted `editor.semanticHighlighting.enabled` from `configuredByTheme` to `true`, This resolved the issue, and now the semantic tokens are displayed correctly as well ^_^**  

![image](https://github.com/Monokai/monokai-pro-vscode/assets/43446377/74bcc62e-b37d-4a42-ab02-c3f567517dae)

Hope this may help ^_^

**Comment by DvdBr3o** [comment]
it works! :)
