### ISSUE TITLE
[ICONS] Different colors regarding file type

### ISSUE THREAD

**Issue by HZooly** [Monokai/monokai-pro-vscode#77]
Hello! I like Monokai Pro, but about Icon Theme, is it planned to add different colors regarding language, type of file etc...

In example, in Material Icon Theme, there're different icons for Angular files (different than classic JS ones).

![Angular Material](https://i.imgur.com/fTunreD.png)

In a real project:

*With Monokai* 
![Monokai Icons](https://i.imgur.com/BetPfZA.png)

*With Material* 
![Material Icons](https://i.imgur.com/YdKnOTj.png)

**Comment by Monokai** [comment]
This is a difficult one. The way these icons are targeted by themes is by matching filenames to `*.directive.js` etc. I don't know if this is right, as you can perfectly have a non-angular file with that name. Also, I've seen Angular repos with different suffixes (e.g. `.drctv.js`). I've added an Angular icon in 1.1.7 and set it to display when a matching `angular` language is active, but as it's just javascript, it doesn't seem to get picked up.

**Comment by HZooly** [comment]
Indeed Material Icons are opinion based so it can becomes tricky to handle different type of files.

**Comment by Monokai** [comment]
Let's close it for now, and see if it comes up again. Thanks!

**Comment by nicentra** [comment]
Any update on this? The fact that e.g. an icon theme like Material has this functionality makes me go back to it even though I like the other Monokai icons more. Simply put I can visually navigate to my components faster due to their colour coding.

Just so much faster seeing a bunch of colour coded Angular shields than 1 uniform array of `*.ts` files
